# Generated by Django 4.2.7 on 2023-12-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@email.com', help_text='required', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default='yourpassword', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='confirmpassword', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='project1',
        ),
    ]
