# Generated by Django 4.2.7 on 2023-12-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_user_email_user_password1_user_password2_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='myproject',
        ),
    ]
